info:
  title: 'Coffee Shop API'
  description: 'This is a Coffee Shop API used by cashiers and baristas'
  version: '1.0.1'
securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []
schemes:
  - http
  - https
host: "cafe.yifanai.com"
basePath: '/v1'
paths:
  /menu:
    get:
      operationId: listMenuItems
      description: 'List all menu items'
      parameters: []
      responses:
        '200':
          description: Successfully listed
          schema:
            type: array
            items:
              $ref: '#/definitions/MenuItem'
        '400':
          description: Bad request
      tags:
        - menu
      produces:
        - application/json
  /orders:
    get:
      operationId: listOrders
      description: 'List all orders'
      parameters: []
      responses:
        '200':
          description: Successfully listed
          schema:
            type: array
            items:
              $ref: '#/definitions/Order'
        '400':
          description: Bad request
      tags:
        - orders
      produces:
        - application/json
    post:
      operationId: createOrder
      description: 'Create an order'
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Order'
      responses:
        '201':
          description: Successfully created
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Bad request (Invalid input)
      tags:
        - order
      consumes:
        - application/json
        - application/x-www-form-urlencoded
        - multipart/form-data
      produces:
        - application/json
  '/orders/{id}':
    get:
      operationId: retrieveOrder
      description: 'Retrieve an order by id'
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this order.
          type: string
      responses:
        '200':
          description: Successfully retrieved
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Bad request (Invalid id)
        '404':
          description: Order not found
      tags:
        - order
      produces:
        - application/json
    put:
      operationId: updateOrder
      description: 'Update an order by id'
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this order.
          type: string
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Order'
      responses:
        '200':
          description: Successfully updated
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Bad request (Invalid input)
        '404':
          description: Order not found
      tags:
        - order
      consumes:
        - application/json
        - application/x-www-form-urlencoded
        - multipart/form-data
      produces:
        - application/json
    patch:
      operationId: partialUpdateOrder
      description: 'Partial update an order by id'
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this order.
          type: string
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Order'
      responses:
        '200':
          description: Successfully updated
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: Bad request (Invalid input)
        '404':
          description: Order not found
      tags:
        - order
      consumes:
        - application/json
        - application/x-www-form-urlencoded
        - multipart/form-data
      produces:
        - application/json
    delete:
      operationId: destroyOrder
      description: 'Delete an order by id'
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this order.
          type: string
      responses:
        '204':
          description: Successfully deleted
        '400':
          description: Bad request (Invalid id)
        '404':
          description: Order not found
      tags:
        - order
swagger: '2.0'
definitions:
  MenuItem:
    type: object
    properties:
      id:
        type: integer
        readOnly: true
      name:
        type: string
        example: Latte
        description: Menu item name (coffee or addition)
      type:
        enum:
          - coffee
          - addition
        type: string
        example: coffee
        description: Menu item type (either coffee or addition)
      price:
        type: number
        example: '4'
        description: Menu item price
  Order:
    type: object
    properties:
      id:
        type: integer
        readOnly: true
      detail:
        type: string
        example: 1 Latte
        description: Order detail (coffee and additions)
      clientName:
        type: string
        example: John Doe
        description: Order customer name
      price:
        type: number
        example: '5'
        description: Order total price
      status:
        enum:
          - unpaid
          - cancelled
          - paid
          - finished
        type: string
        example: unpaid
        description: 'Order status (one of unpaid, cancelled, paid or finished)'
      paymentDetail:
        type: string
        example: Cash
        description: Order payment detail (Payment method and change)
x-components: {}
